stages:
  - deploy-dev




variables:
  HEADER: 'PRIVATE-TOKEN: ${TOKEN_GITLAB}'



deploy dev:
    stage: deploy-dev
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - wget --header="${HEADER}" $ENV_DEVELOP -O .env
        - git config --global user.email "diego.carciente@gmail.com"
        - git config --global user.name "dirlant"
        - git add -f .env
        - dpl --provider=heroku --app=$HEROKU_DEV --api-key=$API_KEY
 
    only:
        - develop


