stages:
  - deploy

variables:
  HEADER: 'PRIVATE-TOKEN: ${TOKEN_GITLAB}'

deploy develop:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

    - wget --header="${HEADER}" ${ENV_DEVELOP} -O .env
    - git config --global user.email "diego.carciente@gmail.com"
    - git config --global user.name "dirlant"
    - git add -f .env
    - git commit -am "add .env"
    - dpl --provider=heroku --app=$HEROKU_DEV --api-key=$API_KEY
  only:
    - develop
