/** @format */

export const Publicity = [
	{
		title: 'Give Away Aleja',
		country: 'colombia',
		image: 'https://i.ibb.co/rkN64KM/giveaway.jpg',
		redirect: 'https://www.instagram.com/p/COTzciKL96M/?igshid=1xnoajozilnuq',
		type_promotion: 'giveaway',
		month: 4,
		day: 7,
	},
	{
		title: 'Give Away Felix',
		country: 'chile',
		image: 'https://i.ibb.co/QN1vyMt/giveawayseguidores.jpg',
		redirect: 'https://www.instagram.com/p/COTwrRRjoXj/',
		type_promotion: 'giveaway',
		month: 4,
		day: 7,
	},
	{
		title: 'Give Away Felix',
		country: 'peru',
		image: 'https://i.ibb.co/QN1vyMt/giveawayseguidores.jpg',
		redirect: 'https://www.instagram.com/p/COTwrRRjoXj/',
		type_promotion: 'giveaway',
		month: 4,
		day: 7,
	},
	{
		title: 'Give Away Felix',
		country: 'ecuador',
		image: 'https://i.ibb.co/QN1vyMt/giveawayseguidores.jpg',
		redirect: 'https://www.instagram.com/p/COTwrRRjoXj/',
		type_promotion: 'giveaway',
		month: 4,
		day: 7,
	},
	{
		title: 'Give Away Felix',
		country: 'venezuela',
		image: 'https://i.ibb.co/QN1vyMt/giveawayseguidores.jpg',
		redirect: 'https://www.instagram.com/p/COTwrRRjoXj/',
		type_promotion: 'giveaway',
		month: 4,
		day: 7,
	},
	{
		title: 'Give Away Felix',
		country: 'mexico',
		image: 'https://i.ibb.co/QN1vyMt/giveawayseguidores.jpg',
		redirect: 'https://www.instagram.com/p/COTwrRRjoXj/',
		type_promotion: 'giveaway',
		month: 4,
		day: 7,
	},
	{
		title: 'Give Away Felix',
		country: 'argentina',
		image: 'https://i.ibb.co/QN1vyMt/giveawayseguidores.jpg',
		redirect: 'https://www.instagram.com/p/COTwrRRjoXj/',
		type_promotion: 'giveaway',
		month: 4,
		day: 7,
	},
	{
		title: 'Give Away Felix',
		country: 'miami',
		image: 'https://i.ibb.co/QN1vyMt/giveawayseguidores.jpg',
		redirect: 'https://www.instagram.com/p/COTwrRRjoXj/',
		type_promotion: 'giveaway',
		month: 4,
		day: 7,
	},
	{
		title: 'Give Away Felix',
		country: 'españa',
		image: 'https://i.ibb.co/QN1vyMt/giveawayseguidores.jpg',
		redirect: 'https://www.instagram.com/p/COTwrRRjoXj/',
		type_promotion: 'giveaway',
		month: 4,
		day: 7,
	},
]
